[project]
name = "freetimer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pydantic>=2.12.3",
    "pyside6>=6.10.0",
    "rich>=14.2.0",
]




[dependency-groups]
dev = [
    "ipykernel>=7.0.1",
    "taskipy>=1.14.1",
]

[tool.taskipy.tasks]
format = 'uvx ruff format'
run = "python main.py"


[tool.ruff]
line-length = 180
